# Generated by Django 5.0 on 2023-12-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
