# Generated by Django 5.0 on 2023-12-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_product_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_site',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
